[general]
server_check_url= http://www.qualcomm.cn/generate_204
dns_exclusion_list=*.cmpassport.com, *.jegotrip.com.cn, *.icitymobile.mobi, id6.me, *.pingan.com.cn, *.cmbchina.com
excluded_routes=239.255.255.250/32, 24.105.30.129/32, 185.60.112.157/32, 185.60.112.158/32, 182.162.132.1/32
resource_parser_url=https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/Scripts/resource-parser.js
fallback_udp_policy=direct

[dns]
no-system
no-ipv6
server=8.8.8.8
server=8.8.4.4
;server=[2001:4860:4860::8888]
;server=[2001:4860:4860::8844]
;doh-server=https://dns.alidns.com/dns-query                                                                             

[policy]

[server_remote]

[filter_remote]
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Advertising/Advertising.list, tag=拦截, force-policy=reject, update-interval=86400, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Proxy/Proxy.list, tag=代理, force-policy=Proxy, update-interval=86400, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/China/China.list, tag=直连, force-policy=direct, update-interval=86400, enabled=true

[rewrite_remote]

[server_local]

[filter_local]
host-suffix, local, direct
ip-cidr, 10.0.0.0/8, direct
ip-cidr, 100.64.0.0/10, direct
ip-cidr, 127.0.0.0/8, direct
ip-cidr, 172.16.0.0/12, direct
ip-cidr, 192.168.0.0/16, direct
ip-cidr, 224.0.0.0/24, direct
ip6-cidr, fe80::/10, direct
geoip, cn, direct
final, proxy

[rewrite_local]

[task_local]

[http_backend]

[mitm]

