[general]
server_check_url=http://www.qualcomm.cn/generate_204
resource_parser_url= https://cdn.jsdelivr.net/gh/KOP-XIAO/QuantumultX@master/Scripts/resource-parser.js
geo_location_checker=http://ip-api.com/json/?lang=zh-CN, https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/Scripts/IP_API.js

[dns]
no-system
no-ipv6
server=119.29.29.29
server=223.5.5.5
server=8.8.8.8
server=1.1.1.1
server=80.80.80.80
;server=[2001:4860:4860::8888]
;server=[2001:4860:4860::8844]
;doh-server=https://dns.alidns.com/dns-query

[policy]

[server_remote]

[filter_remote]
https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Filter/Unbreak.list, tag=Unbreak, update-interval=86400, enabled=true
https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Filter/Guard/Advertising.list, tag=Advertising, force-policy=reject, update-interval=86400, enabled=true
https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Filter/Guard/Privacy.list, tag=Privacy, force-policy=reject, update-interval=86400, enabled=true
https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Filter/Guard/Hijacking.list, tag=Hijacking, force-policy=reject, update-interval=86400, enabled=true
https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Filter/Global.list, tag=🇺🇳Global, force-policy=proxy, update-interval=86400, enabled=true
https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Filter/China.list, tag=🇨🇳China, force-policy=direct, update-interval=86400, enabled=true

[rewrite_remote]

[server_local]

[filter_local]
ip-cidr, 10.0.0.0/8, direct
ip-cidr, 127.0.0.0/8, direct
ip-cidr, 172.16.0.0/12, direct
ip-cidr, 192.168.0.0/16, direct
ip-cidr, 224.0.0.0/24, direct
geoip, cn, direct
final, proxy

[rewrite_local]

[task_local]

[http_backend]

[mitm]
